### ISSUE TITLE
テストケース指定方法の改良

### ISSUE THREAD

**Issue by tsutaj** [tsutaj/statements-manager#4]
- {@samples.sample_00_in} とか {@samples.sample_01_in} とかやってたら結局目 diff 失敗してどこかでミスりそう、いい方法ないんか？
- 出力のみの場合や、インタラクティブなどの特殊ケースにも対応させる仕組みも必要

**Comment by tsutaj** [comment]
そもそもインタラクティブなら表を書かないといけないはず。(例えば下に書いた感じのやつ)

インタラクティブの場合は、この表がかいてある markdown ファイルを指定してもらえばいい？

|Output|Judge|
|---|---|
||```5```|
|```3 2```<br />```1 2 3 4 5```||
||```-1```|

**Comment by tsutaj** [comment]
入力が与えられない問題も存在するので、必ずしも入力・出力がどちらも存在するわけではない。  
(ところで出力がない問題はあるのか？)

サンプルはこんな感じで指定してもらうのがいいかな・・・

```toml
[problem.samples]
    id = "sample_00"
    type = "default" # "default", "input-only", "output-only", "interactive"
    input_path = "path/to/sample.in" # "default" および "input-only" で必要
    output_path = "path/to/sample.out" # "default" および "output-only" で必要
    interactive_path = "path/to/interactive.md" # "interactive" で必要
```

それで、問題文側では `{@samples.sample_00}` みたいに呼び出すことでよしなに入出力 (もしくは、インタラクティブの md) を貼り付ける感じ。in と out で 2 回似たようなのを書く必要はないし、今よりはマシになりそう。
