### ISSUE TITLE
CI との連携を考える

### ISSUE THREAD

**Issue by tsutaj** [tsutaj/statements-manager#52]
例えば

- Markdown を Git で編集
- 誰かにレビューしてもらうために PR を出す
- 承認されたら (マージされたら) CI で本アプリケーションを回して問題文情報を更新

pip (または GitHub) にすでに乗っけているので、上記のフローはやろうと思えば比較的容易にできるはず。とはいえ雛形があった方が親切なので、一旦書いてみて使用感を確かめたい。

あと、CI を回すならエラー処理がまともでないといけない。

**Comment by tsutaj** [comment]
最も上の階層で `ss-manager` を動かすなら次のような実装になるだろう。  
(Google Docs 用の credentials は新たに設定不要であると仮定)

```yaml
# statements-manager を動かし、変更点があれば commit & push する
name: update-statements

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install statements-manager
    - name: Run statements-manager
      run: |
        ss-manager run ./
    - name: Commit files
      run: |
        git add --all
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "[ci skip] [bot] Updating to ${{ github.sha }}."
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
```
